### PR TITLE
Copied Linked_List.py, fixed bug in append, Created chaining hash wit…

### PR DESCRIPTION
**Pull request by jchu42**
…h linked list

I love and hate my insert and delete implementations, but how else would I change/remove elements in the linked list?

### CODE REVIEW

**Comment by cassLaffan** [comment]
Small changes are needed before you merge, particularly your while (True)s.

**Comment by jchu42** [comment]
I think it should already be guaranteed to terminate, and I'm not sure how else to do it without adding more functions to LinkedList. What changes are needed / what issue does it have?

**Comment by cassLaffan** [comment]
It's more that it's necessary to get into the habit of avoiding while(True) at all costs; there are ways to write these statements. If it needs another function, then c'est la vie~

**Comment by jchu42** [comment]
gotcha; I'll probably add a remove(element) function to LinkedList then; should be fun, and make the hashtable functions more elegant

**Comment by jchu42** [comment]
while true loops have been removed

**Pull request merged**
